[global]
   workgroup = WORKGROUP
   server string = Honeypot Gateway Samba
   log file = /var/log/samba/log.%m
   max log size = 50
   map to guest = Bad User
   guest account = nobody
   server role = standalone server
   disable netbios = yes
   smb ports = 445

[public]
   path = /srv/public
   browsable = yes
   writable = no
   guest ok = yes
   read only = yes
