[supervisord]
nodaemon=true
childlogdir=/var/log/supervisor

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd.err

[program:smbd]
command=/usr/sbin/smbd --foreground --no-process-group
autorestart=true
stdout_logfile=/var/log/supervisor/smbd.log
stderr_logfile=/var/log/supervisor/smbd.err
